//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_Factory7_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeShift
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ShiftID { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual shifts shifts { get; set; }
    }
}
